version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: mongoadmin
      DB_PASS: password123
      DB_NAME: prueba_tecnicadb
      SECRETKEY: palabraultrasecreta
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: